name: Call reusable docker build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: clubcedille/cedille-workflows/.github/workflows/external-build-push-ghcr.yaml@master
    with:
      container-name: saveursdegenie.etsmtl.ca
      pr-head-sha: ${{ github.event.pull_request.head.sha || '' }}
      pr-head-ref: ${{ github.event.pull_request.head.ref || '' }}
      context: .
      file: Dockerfile
      branch: master
    secrets:
      GIT_AUTH_TOKEN: ${{ secrets.GHCR_PAT }}
